# Generated by Django 5.2.1 on 2025-06-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airapp', '0002_flight_remove_book_bus_book_flight_delete_bus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='flight_name',
            new_name='bus_name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='sent_on',
        ),
        migrations.AlterField(
            model_name='book',
            name='nos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='nos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='rem',
            field=models.PositiveIntegerField(),
        ),
    ]
